### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by frozenspider** [scala-ide/scala-refactoring#189]
From SBT prompt, launched inside latest master (30fd14d9b85b0a750cf2cb52fe6b2151f97f082d)
```
> ++ 2.11.8
[info] Setting version to 2.11.8
[info] Reapplying settings...
[info] Set current project to org.scala-refactoring.library (in build file:/D:/_Home/eclipse-workspaces/workspace-FS/scala-refactoring-master/)
> package
[info] Updating {file:/D:/_Home/eclipse-workspaces/workspace-FS/scala-refactoring-master/}scala-refactoring-master...
[info] Resolving org.scala-lang#scala-library;2.11.8 ...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 94 Scala sources and 1 Java source to D:\_Home\eclipse-workspaces\workspace-FS\scala-refactoring-master\target\scala-2.11\classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.8. Compiling...
[info]   Compilation completed in 9.94 s
[trace] Stack trace suppressed: run last compile:packageBin for the full output.
[error] (compile:packageBin::packageOptions) Nonzero exit value: 128
[error] Total time: 48 s, completed 28.02.2017 4:21:36
> last compile:packageBin
java.lang.RuntimeException: Nonzero exit value: 128
        at scala.sys.package$.error(package.scala:27)
        at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134)
        at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
        at $3324acd55f2016653e59$$anonfun$$sbtdef$1$$anonfun$1.apply(D:\_Home\eclipse-workspaces\workspace-FS\scala-refactoring-master\build.sbt:108)
        at $3324acd55f2016653e59$$anonfun$$sbtdef$1$$anonfun$1.apply(D:\_Home\eclipse-workspaces\workspace-FS\scala-refactoring-master\build.sbt:102)
        at sbt.Using.apply(Using.scala:24)
        at $3324acd55f2016653e59$$anonfun$$sbtdef$1.apply(D:\_Home\eclipse-workspaces\workspace-FS\scala-refactoring-master\build.sbt:102)
        at $3324acd55f2016653e59$$anonfun$$sbtdef$1.apply(D:\_Home\eclipse-workspaces\workspace-FS\scala-refactoring-master\build.sbt:101)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:packageBin::packageOptions) Nonzero exit value: 128
>
```

**Comment by sschaef** [comment]
I can't reproduce that. Are you on Java8?

Maybe it is also a Windows problem. @wpopielarski Can you reproduce that?

**Comment by wpopielarski** [comment]
unfortunately it works for me too `Done packaging`

**Comment by frozenspider** [comment]
Yes, forgot to mention it - I'm using Windows 8.1 and Java 1.8.0_121

**Comment by wpopielarski** [comment]
personally I tested it on Win 10.0.14393 but surely it is not a problem. Maybe it's sbt version problem? Mine is 0.13.8

**Comment by frozenspider** [comment]
Found the cause - I downloaded master state as ZIP from GitHub, so there were no `.git`. It seems that git is somehow used during the packaging process - when I cloned entire repo, packaging works.
It should probably be optional on mentioned explicitly though.

**Comment by wpopielarski** [comment]
good to hear it
